// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sryajzwtfbderpixriqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyeWFqend0ZmJkZXJwaXhyaXFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMzI0ODgsImV4cCI6MjA2NjkwODQ4OH0.8eZAgU-7RYd_GaHjkIXZTxGzC5YAOdEP3kwsXjjbUbE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});